### ISSUE TITLE
k eks nodes segfaults

### ISSUE THREAD

**Issue by rothgar** [surajincloud/kubectl-eks#38]
I thought I did something wrong with an older version of this plugin but I just set up a brand new 1.27 cluster using karpenter and I get the same segfault output

```
k eks nodes
NAME     INSTANCE-TYPE     OS     CAPACITY-TYPE     REGION     AMI-ID     AMI-NAME     AGE
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x37fb074]

goroutine 1 [running]:
github.com/surajincloud/kubectl-eks/cmd.nodes(0x5aa6740?, {0x3f6b1fc?, 0x0?, 0x0?})
        /home/runner/work/kubectl-eks/kubectl-eks/cmd/nodes.go:67 +0x794
github.com/spf13/cobra.(*Command).execute(0x5aa6740, {0x5bafc18, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x5aa6a20)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/surajincloud/kubectl-eks/cmd.Execute()
        /home/runner/work/kubectl-eks/kubectl-eks/cmd/root.go:25 +0x25
main.main()
        /home/runner/work/kubectl-eks/kubectl-eks/main.go:6 +0x17
```
I haven't dug into it to find out where it's happening but I thought I would open this ticket to track it in case you already know about the problem.

I don't have problems with getting the nodes regularly
```
k get nodes
NAME                                            STATUS   ROLES    AGE     VERSION
ip-192-168-100-101.us-west-2.compute.internal   Ready    <none>   7m30s   v1.27.1-eks-2f008fe
ip-192-168-132-133.us-west-2.compute.internal   Ready    <none>   7m28s   v1.27.1-eks-2f008fe
ip-192-168-158-101.us-west-2.compute.internal   Ready    <none>   107m    v1.27.1-eks-2f008fe
ip-192-168-172-71.us-west-2.compute.internal    Ready    <none>   107m    v1.27.1-eks-2f008fe
ip-192-168-78-24.us-west-2.compute.internal     Ready    <none>   7m28s   v1.27.1-eks-2f008fe
```

**Comment by surajnarwade** [comment]
@rothgar thanks for pointing out the issue, I will handle this condition in my upcoming PR. I will be presenting this session at AWS London Summit, Community Lounge, Glad we found this.

I just spinned up fresh EKS Cluster(1.27), can you point me to a karpenter doc which you followed to create the nodes?

**Comment by rothgar** [comment]
Here's the main docs https://karpenter.sh/v0.27.5/getting-started/getting-started-with-karpenter/

I used [eksdemo](https://github.com/awslabs/eksdemo) to create the cluster and install karpenter

```
eksdemo create cluster karpenter-cluster
eksdemo install autoscaling karpenter -c karpenter-cluster
```

**Comment by surajnarwade** [comment]
thank you so much, didn't know eksdemo, really helpful. will fix the issue soon.

**Comment by surajnarwade** [comment]
@rothgar this is solved in https://github.com/surajincloud/kubectl-eks/releases/tag/v0.2.1

**Comment by rothgar** [comment]
Works for me! Thanks :raised_hands:
